yarnPath: .yarn/releases/yarn-3.2.3.cjs
nodeLinker: node-modules
packageExtensions:
  "@graphql-codegen/cli@*":
    peerDependencies:
      "@types/node": "^18.7.23"
      ts-node: "^10.9.1"
      typescript: "^4.8.4"
  graphql-config@*:
    peerDependencies:
      "@types/node": "^18.7.23"
      typescript: "^4.8.4"
npmScopes:
  leanil:
    npmAuthToken: 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
    npmRegistryServer: "https://npm.pkg.github.com"
