nodeLinker: node-modules

npmScopes:
  Kristofy:
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "@graphql-codegen/cli@*":
    peerDependencies:
      "@types/node": ^18.7.23
      ts-node: ^10.9.1
      typescript: ^4.8.4
  graphql-config@*:
    peerDependencies:
      "@types/node": ^18.7.23
      typescript: ^4.8.4

yarnPath: .yarn/releases/yarn-sources.cjs
